
'use client';

import { useMemo } from 'react';
import { buildRpmUrl, getLayerStyles } from '@/lib/avatar-engine';
import { cn } from '@/lib/utils';
import type { User, GeneratedCosmetic, CosmeticItem } from '@/lib/types';
import { COSMETIC_ITEMS } from '@/lib/avatar-cosmetics';
import Image from 'next/image';

interface TwinskieAvatarProps {
  user: User;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
}

const SIZE_MAP = {
  sm: 'w-24 h-24',
  md: 'w-48 h-48',
  lg: 'w-64 h-64',
  xl: 'w-80 h-80',
};

/**
 * The TwinskieAvatar component is a client-side renderer. It does not call OpenAI directly.
 * Its role is to display the final avatar by layering multiple cosmetic assets on top of a base image.
 * The generation of these assets (e.g., SVG code for AI cosmetics) and editing of the base image
 * (e.g., background removal) happens in upstream AI flows that use OpenAI (GPT-4o-mini and DALL-E 2).
 * This component simply assembles the results of OpenAI's work.
 */
export function TwinskieAvatar({ user, size = 'md', className }: TwinskieAvatarProps) {
  const dimensions = SIZE_MAP[size];

  const activeLayers = useMemo(() => user.avatarLayers ?? {}, [user.avatarLayers]);

  // 1. Get active AI-generated cosmetics (SVG overlays generated by OpenAI GPT-4o-mini)
  const activeAiCosmetics = useMemo(() => {
    const aiData = user.aiGeneratedCosmetics ?? {};
    return Object.keys(activeLayers)
      .filter((id) => activeLayers[id] === true && aiData[id])
      .map((id) => aiData[id] as GeneratedCosmetic);
  }, [activeLayers, user.aiGeneratedCosmetics]);

  // 2. Get active static cosmetics (from /lib/avatar-cosmetics.ts)
  const activeStaticCosmetics = useMemo(() => {
    return COSMETIC_ITEMS.filter(item => activeLayers[item.id] === true);
  }, [activeLayers]);
  
  // Combine all active cosmetics for effect calculation
  const allActiveCosmetics = [...activeAiCosmetics, ...activeStaticCosmetics];

  // 3. Memoize the base RPM URL. The base image may have been processed by OpenAI (DALL-E 2) for background removal.
  const rpmUrl = useMemo(() => {
    if (!user.avatarUrl) return '';
    return buildRpmUrl(user.avatarUrl, []);
  }, [user.avatarUrl]);

  // 4. Combine CSS effects from all active cosmetics
  const combinedEffects = useMemo(() => {
    const effects: React.CSSProperties = {};
    const backgrounds: string[] = [];

    allActiveCosmetics.forEach(cosmetic => {
        // Use 'in' operator for type guarding. This checks if the property exists on the object.
        // AI-generated cosmetics have a `cssEffects` object.
        if ('cssEffects' in cosmetic && cosmetic.cssEffects) {
          const css = cosmetic.cssEffects;
          if (css.background) {
              backgrounds.push(css.background);
          }
          if (css.boxShadow) {
              effects.boxShadow = `${effects.boxShadow || ''}, ${css.boxShadow}`.trim().replace(/^,/, '');
          }
          if (css.border) {
              effects.border = css.border;
          }
          if (css.filter) {
              effects.filter = `${effects.filter || ''} ${css.filter}`.trim();
          }
        } 
        // Static cosmetics have individual effect properties.
        else {
          const staticCosmetic = cosmetic as CosmeticItem;
          if (staticCosmetic.backgroundGradient) {
              backgrounds.push(staticCosmetic.backgroundGradient);
          }
          if (staticCosmetic.boxShadow) {
              effects.boxShadow = `${effects.boxShadow || ''}, ${staticCosmetic.boxShadow}`.trim().replace(/^,/, '');
          }
          if (staticCosmetic.border) {
              effects.border = staticCosmetic.border;
          }
        }
    });

    if (backgrounds.length > 0) {
        effects.background = backgrounds.join(', ');
    }

    return effects;
  }, [allActiveCosmetics]);


  if (!user.avatarUrl) {
    return (
      <div className={cn("bg-secondary animate-pulse rounded-xl", dimensions, className)} />
    );
  }

  return (
    <div 
        className={cn("relative flex items-center justify-center rounded-lg", dimensions, className)}
        style={combinedEffects}
    >
      
      {/* 1. Base Ready Player Me Render (Potentially background-removed by DALL-E 2) */}
      <img
        src={rpmUrl}
        alt={`${user.userName}'s Avatar`}
        className="relative z-10 w-full h-full object-contain"
      />

      {/* 2. AI-Generated SVG Overlays (Generated by GPT-4o-mini) */}
      {activeAiCosmetics
        .map((cosmetic) => (
          <div
            key={cosmetic.id}
            style={{ 
              ...getLayerStyles(cosmetic.position), 
            }}
            className="z-20"
            dangerouslySetInnerHTML={{ __html: cosmetic.svgCode }}
          />
        ))}
        
      {/* 3. Static Image Overlays (from store, etc.) */}
      {activeStaticCosmetics
        .filter(item => item.type === 'overlay' && item.imageUrl)
        .map((item) => (
             <img
                key={item.id}
                src={item.imageUrl}
                alt={item.name}
                className="absolute z-20"
                style={{ ...getLayerStyles('body') }} // Assuming most overlays are 'body' type
            />
        ))}
    </div>
  );
}
